Update docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -48,7 +48,7 @@ jobs:
             docker tag $IMAGE $TARGET
 
             echo "🔍 Running Trivy scan on $TARGET ..."
-            trivy image --no-progress --format table --output trivy-reports/${NAME}-${TAG}.txt $TARGET || echo "Scan failed for $TARGET" > trivy-reports/${NAME}-${TAG}.txt
+            trivy image --no-progress --format table --output trivy-reports/${NAME}-${TAG}.txt $IMAGE || echo "Scan failed for $IMAGE" > trivy-reports/${NAME}-${TAG}.txt
 
             docker push $TARGET
             echo "✅ Pushed $TARGET"
